---
- hosts: all
  tasks:
          - name: Installing needed utilities
            apt:
                    name:
                            - python
                            - git
                            - openssh-server
                    state: present
                    autoclean: yes
         - name: Installing chromedriver and selenium
           commands: sh installing_chrome.sh
